services:
  windows:
    build:
      context: .
      dockerfile: Dockerfile
    image: hkccr.ccs.tencentyun.com/safore-com/win
    container_name: windows
    environment:
      VERSION: win11
      LANGUAGE: Chinese
      DISK_SIZE: 256G
      RAM_SIZE: 8G
      CPU_CORES: 4
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./data:/storage
      - ./instance:/shared